src/Observables.jl
Though I just second guessed myself and wondered if it should be `valtype`...
=> Adds eltype

src/Observables.jl
This is used in a forthcoming PR to WebIO to enable syncing observables across Widgets
n.b. eltype(obs) change is also in #7
=> Adds an id to the observable

.travis.yml
release will change, but since the package supports 0.5 in
REQUIRE it should continue to be tested
=> use version numbers instead of release on travis

src/Observables.jl
Same as for JSExpr: as it's a dependency of precompilable packages, it should also be precompilable.
=> add precompilation

src/Observables.jl, test/runtests.jl
A function that transforms an Observable to another that updates asynchronously as and when there is a chance to do so, discarding all but the last `n` updates.
```julia
o = Observable(0)
function compute_something(x)
for i=1:10^8 rand() end # simulate something expensive
println("updated with $x")
end
o_latest = async_latest(o, 1)
on(compute_something, o_latest) # compute something on the latest update
for i=1:5
o[] = i # this is asynchronous
end
updated with 5 # only the last one got fired.
```
Somehow Julia takes offence if I use an anonymous function on `o_latest`
```julia
o = Observable(0)
o_latest = async_latest(o, 1)
on(o_latest) do x
for i=1:10^8 rand() end # simulate something expensive
println("updated with $x")
end
for i=1:5
o[] = i
end
ERROR (unhandled task failure): …
```
=> async_latest

src/Observables.jl
Otherwise, `map` errors every time `f` is type unstable. I think we shouldn't rely on inference to determine the result, so I guess the correct thing is to use a `Observable` of type `Any`.
=> fix map for type unstable functions

src/Observables.jl
Julia does seem to have problems with errors `setindex(obs, val)` - it might stack overflow or just silently freeze. A try catch and manual error display seems to solve this
=> catch + print errors manually

src/time.jl
To fix https://github.com/JuliaGizmos/Interact.jl/issues/274. A throttled `Observable` should get "set" after the delay if the input observable was triggered, even if the underlying value has not changed (meaning it will be set to the same value).
=> do not require changed value to update throttled observable

docs/make.jl, docs/src/index.md, src/Observables.jl, src/macros.jl, src/time.jl
I missed `throttle()` from the documentation and tried to add it but encountered some issues, that I try to resolve in this PR.
Firstly, the documentation site is outdated. The last build was 11 month ago, neither releases and "latest" versions did not get their documentation.
I think the issue is, that the macros have doctests, which fail, because `using Observables` is missing.
I solved it with removing the `jldoctest` tag.
Secondly I wanted to add `throttle()` to the docs and thought that it would be easier to use `@autodocs`
Thirdly, I fixed a deprication warning in `make.jl`.
=> fix documentation

src/Observables.jl, test/runtests.jl
e.g., this was failing:
```julia
@testset "copy" begin
obs = Observable{Any}(:hey)
obs_copy = copy(obs)
obs[] = 1
@test obs_copy[] == 1
end
```
=> preserve eltype on copy

docs/src/index.md, src/Observables.jl, src/observablepair.jl, test/runtests.jl
We still have the problem that it's hard to keep track of the connections we make with Observables and to clean them up after use. This PR seeks to help while staying close enough to the previous API, that it hopefully doesn't break too much code using Observables.
The main change is that `on` returns a new type `ObserverFunction`. This wraps the closure `Function` which is normally returned by `on`. It stores the function, the observable that is being listened to, and a `weak` flag. If the `weak` flag is set via `on(..., weak = true)`, the `ObserverFunction` will call `off(observable, closure)` when finalized.
This allows for some easy housekeeping. Imagine some large plotting object that creates multiple connections via `on`. We just have to `push!` all weak `ObserverFunction`s into one …
=> Introduce self-deregistering closures for on / onany

src/Observables.jl, src/observablepair.jl
The old implementation of ObservablePairs seems unnecessarily
complicated. Perhaps more importantly, this change allows us
to eliminate the `notify` kwarg of `setindex!`, which should reduce
type-diversity and may help reduce latency.
EDIT: I also suspect that the current implementation has a bug if you make two pairs, one with `a` and `b` and the other with `b` and `c` and use the same update function for both. This implementation should not suffer from any such problems.
=> Reimplement ObservablePairs and eliminate notify keyword

Project.toml, src/Observables.jl, test/runtests.jl
`connect!` did the opposite of what was described in the docstring.
The docstring is more consistent with the convention of the modified
argument being first, so we go with the docstring and change the code.
While technically this is a bugfix, it could trigger StackOverFlow
errors, so let's call this a breaking change.
=> Fix `connect!`

src/Observables.jl, test/runtests.jl
This can be handy when trying to figure out where some `var"#31#32"`
function was defined.
=> Add a convenience utility for locating the origin of methods

src/Observables.jl
Previously we had `notify!`, which had the `!` because it called
`setindex!`. But notification does not require mutation of the owner.
This moves the work of notification from `setindex!` to `notify` and
deprecates `notify!`.
=> Move notification to `notify`

src/Observables.jl, test/runtests.jl
This addresses a comment made in
https://github.com/JuliaGizmos/Observables.jl/pull/48#issuecomment-699608226
by implementing storage for the ObserverFunctions
added by `map`.
This also adds optional precompilation support for observables,
precompiling the methods based on the `T` in `Observable{T}`.
Since `on` doesn't call the function right away, I don't think there's a way to precompile
them automatically (there would be, if `on` immediately called the callback, but of course
that has issues too). So it's a step you have to perform manually.
=> Let `map` store ObserverFuncs & add precompile

src/Observables.jl
It's not entirely obvious whether this is the right thing to do, but the
idea here is that by ensuring that `map` gets specialized
for their function argument, it makes everything more precompilable.
Conversely, `on` immediately drops use of any specific information about
`f`, so we avoid specialization.
It might not be as important with precompilation of observables, so it's
worth being a bit skeptical about this.
=> Adjust specialization of `on` and `map`

src/Observables.jl, test/runtests.jl
There are several things that are a bit complicated/confusing about
`map` and `map!`:
- the `init` keyword also affects whether `f` runs (controlling the initial
value is not orthogonal to execution, which spells trouble for
functions with side effects)
- in contrast with `Base.map!`, `map!(f, dest::Observable, args..)`
does not eagerly update `dest`---that doesn't happen until one of
`args` updates
- `map` always yields an `Observable{Any}`, somewhat in contradiction
to the behavior of `Base.map` (see #34)
This redesigns `map` and `map!` to address these issues (fixes #34).
It is a breaking change, although I've put in a depwarn for the case
where `init` was supplied. (The non-deprecated changes are so fundamental
that this may not be useful, however.)
Now:
- `map` always runs `f` on …
=> Rework `map` and `map!`

src/Observables.jl, test/runtests.jl
`latest_change(obs)` to only observe value changes. Ref #5
=> Update on value change

src/Observables.jl, test/runtests.jl
This causes named functions to print by name, but anonymous ones to
print via file:line. This may make it easier to know
where each comes from.
=> Custom display for ObserverFunction

.github/workflows/CI.yml, .github/workflows/documenter.yml, Project.toml, docs/src/index.md, src/Observables.jl, test/runtests.jl
- add `ignore_equal_values` to Observable constructor, which implements https://github.com/JuliaGizmos/Observables.jl/pull/79 without adding a new type
- add `PriorityObservable` from Makie without adding a new type (from [PriorityObservable.jl](https://github.com/JuliaPlots/Makie.jl/blob/master/src/interaction/PriorityObservable.jl)). One can now simply add `on(f, priority::Int=...)`, to register a callback with priority.
- add `on(f, obs; update=true)`, to call `f(obs[])` immediately.
- improve compile times quite a bit
Based on `sd/compile-time` not for the best reasons, besides it being a bit easier
=> api improvements

src/Observables.jl
`setexcludinghandlers!` was removed in https://github.com/JuliaGizmos/Observables.jl/pull/84/files#diff-717dd66a485f4523942145feb17dfcebc7bf9e137ee03fa29c1ef8c8c3b1cad6L272 but it's unclear how to update code that uses `setexcludinghandlers!`.
This pull request just puts the old code back, since e.g. `WebIO` still relies on `setexcludinghandlers!`.
=> Reintroduce setexcludinghandlers!

src/Observables.jl
`nameof(some_struct)` doesn't work on julia 1.6
=> fix show for custom callback functors

src/Observables.jl
This adds the `priority` keyword to `map`.
I think I made these changes alongside https://github.com/MakieOrg/Makie.jl/pull/3084 but forgot to open a pr.  Without them `lift` and `map` are inconsistent between the `map(f, scene/plot, obs...)` and `map(f, obs...)` versions, as one supports priority and the other does not.
Will fix map/priority related errors in https://github.com/MakieOrg/Makie.jl/pull/3246.
@SimonDanisch Would be good to have this merged before the next Makie release
=> Add priority to map

src/Observables.jl
The custom obsfunc was turning up sporadically on older julia versions.
We somehow stopped appending the inputs, I suppose by mistake, so I'm adding it back here.
=> fix custom obsfuncs + add back obs.inputs

src/Observables.jl, test/runtests.jl
Turns out, objectid gets re-used after some time, so if one saves the ID for a longer time, and I suppose if the observable goes out of scope, it can happen that an observable with the same ID turns up!
=> Get an actualy unique ID
